//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WriteError", ReplyAction="http://tempuri.org/IService1/WriteErrorResponse")]
        void WriteError(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Exchange", ReplyAction="http://tempuri.org/IService1/ExchangeResponse")]
        System.Data.DataSet Exchange(System.DateTime date1, System.DateTime date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckInformation", ReplyAction="http://tempuri.org/IService1/CheckInformationResponse")]
        bool CheckInformation(string Code, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPower", ReplyAction="http://tempuri.org/IService1/GetPowerResponse")]
        string GetPower(string Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BookUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BookUI.ServiceReference1.IService1>, BookUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteError(string message) {
            base.Channel.WriteError(message);
        }
        
        public System.Data.DataSet Exchange(System.DateTime date1, System.DateTime date2) {
            return base.Channel.Exchange(date1, date2);
        }
        
        public bool CheckInformation(string Code, string Password) {
            return base.Channel.CheckInformation(Code, Password);
        }
        
        public string GetPower(string Code) {
            return base.Channel.GetPower(Code);
        }
    }
}
